# Generated by Django 5.1.5 on 2025-02-05 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anc_date', models.DateField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Missed', 'Missed')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='maternityTrack.division')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('husband_name', models.CharField(max_length=255)),
                ('husband_phone', models.CharField(max_length=20)),
                ('couple_no', models.CharField(max_length=50, unique=True)),
                ('nid_number', models.CharField(max_length=50, unique=True)),
                ('ward_number', models.CharField(max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('husband_blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('husband_earning', models.DecimalField(decimal_places=2, help_text="Husband's earning per month", max_digits=10)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_patients', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maternityTrack.district')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maternityTrack.union')),
            ],
        ),
        migrations.CreateModel(
            name='MotherDeath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_death', models.DateField()),
                ('cause_of_death', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maternityTrack.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ChildBirth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('status', models.CharField(choices=[('Alive', 'Alive'), ('Stillborn', 'Stillborn')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maternityTrack.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CheckupReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anc_checkup_number', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st ANC'), (2, '2nd ANC'), (3, '3rd ANC'), (4, '4th ANC')], null=True)),
                ('bp', models.CharField(max_length=20)),
                ('rbs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pulse', models.IntegerField()),
                ('ifa', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('thyroid_disease', models.BooleanField()),
                ('heart_disease', models.BooleanField()),
                ('bronchial_asthma', models.BooleanField()),
                ('kidney_disease', models.BooleanField()),
                ('epilepsy', models.BooleanField()),
                ('placenta_location', models.CharField(max_length=255)),
                ('history_iud', models.BooleanField()),
                ('history_stillbirth', models.BooleanField()),
                ('history_preclampsia', models.BooleanField()),
                ('history_eclampsia', models.BooleanField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maternityTrack.ancschedule')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkup_reports', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maternityTrack.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PregnancyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('husband_age', models.IntegerField()),
                ('pregnancy_count', models.PositiveIntegerField(default=1, help_text='Pregnancy Number')),
                ('menstruation_off_duration', models.IntegerField(help_text='How long is menstruation off (in months)')),
                ('womb_count', models.IntegerField(help_text='How many wombs')),
                ('living_children', models.IntegerField(help_text='Number of living children')),
                ('last_child_age', models.IntegerField(blank=True, help_text="Last child's age", null=True)),
                ('normal_delivery_count', models.IntegerField(help_text='Previous normal deliveries')),
                ('c_section_count', models.IntegerField(help_text='Previous C-sections')),
                ('d_and_c_count', models.IntegerField(help_text='Previous D&C/MRI procedures')),
                ('preferred_delivery_place', models.CharField(choices=[('Hospital', 'Hospital'), ('Clinic', 'Clinic'), ('Home', 'Home')], max_length=20)),
                ('tt_dose_count', models.IntegerField(help_text='How many TT doses taken')),
                ('family_planning_after_delivery', models.BooleanField(default=False, help_text='Willing to take family planning after delivery?')),
                ('physical_problem', models.TextField(blank=True, help_text='Any physical problems?', null=True)),
                ('last_period_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='maternityTrack.patient')),
            ],
        ),
        migrations.AddField(
            model_name='ancschedule',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maternityTrack.pregnancyrecord'),
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_offices', to='maternityTrack.union')),
            ],
        ),
        migrations.CreateModel(
            name='Upazilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upazillas', to='maternityTrack.district')),
            ],
        ),
        migrations.AddField(
            model_name='union',
            name='upazilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unions', to='maternityTrack.upazilla'),
        ),
        migrations.AddField(
            model_name='patient',
            name='upazilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maternityTrack.upazilla'),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('word_no', models.PositiveIntegerField(choices=[(1, 'Ward No: 1'), (2, 'Ward No: 2'), (3, 'Ward No: 3')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='maternityTrack.union')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maternityTrack.village'),
        ),
    ]
