# Generated by Django 5.1.5 on 2025-02-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maternityTrack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ancschedule',
            old_name='patient',
            new_name='pregnancy_record',
        ),
    ]
