# Generated by Django 5.1.5 on 2025-02-07 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternityTrack', '0003_deliveryrecord_remove_motherdeath_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maternityTrack.division'),
        ),
    ]
