# Generated by Django 5.1.5 on 2025-02-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maternityTrack', '0004_patient_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='ward_number',
        ),
    ]
