# Generated by Django 5.1.5 on 2025-02-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maternityTrack', '0005_remove_patient_ward_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregnancyrecord',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
