# Generated by Django 5.1.5 on 2025-02-11 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternityTrack', '0006_rename_create_at_pregnancyrecord_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkupreport',
            name='anc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maternityTrack.ancschedule'),
        ),
    ]
