# Generated by Django 5.1.5 on 2025-02-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('maternityTrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='upazila',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_complex', to='maternityTrack.upazilla'),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='health_complex',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_bank', to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='ambulanceservice',
            name='health_complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_services', to='hospital.hospital'),
        ),
    ]
